### ISSUE TITLE
Using Press This Extended with https?

### ISSUE THREAD

**Issue by DrewClark** [kraftbj/press-this-extended#24]
I'm having troubles using Press This Extended on secure (https) sites. Works fine with http, but with https no text or images are carrying over when i hit the "press this" bookmarklet that I've got.

I'm using version 1.1, with WP 4.7.2

And help would be much appreciated!

**Comment by kraftbj** [comment]
This would be an issue with Press This itself (not Press This Extended) as far as I know. Does disabling the plugin resolve it?

I'm going to close this, but happy to reopen with additional info.
